### PR TITLE
Coarse grained locking in update storage component

### PR DESCRIPTION
**Pull request by marc-casperlabs**
This makes the locking more coarse, to avoid potential future issues with locking order and reduce the number of spots where locks are acquired.

References to `Indices` are being passed around in some places, these should be considered to be similar to an LMDB transaction.

### CODE REVIEW

**Comment by rafal-ch** [comment]
These changes LGTM :+1:

**Comment by marc-casperlabs** [comment]
Was the underlying branch force pushed again or did we target the wrong thing? There's suddenly a lot of conflicts on files that we did not touch 🤔

**Comment by marc-casperlabs** [comment]
I'll be force-pushing to this branch, squashing the ~four~ three commits

62e83e052dd0e78ff023b1323d760aab3de61d1c
687fd147c4e1908bcd8635229469ab666ed7f9a7
151bca75a36cd5bc3051418cdd851fb303918a6e

to make it easier for @dwerner to rebase.

**Comment by dwerner** [comment]
Manually cherry-picked this over to https://github.com/casper-network/casper-node/pull/2680

**Pull request closed without merging**
